# yaml-language-server: $schema=https://www.schemastore.org/pnpm-workspace.json
packages: []
linkWorkspacePackages: true
syncInjectedDepsAfterScripts:
  - "@glektarssza/*"
preferWorkspacePackages: true
includeWorkspaceRoot: true
ignorePnpmfile: true
